### ISSUE TITLE
Move to Nokogiri::XSLT and remove ruby-xslt dependency

### ISSUE THREAD

**Issue by CAMOBAP795** [metanorma/metanorma-m3d#10]
We can simplify our dependency list and skip some problem with `ruby-xslt` on windows https://github.com/metanorma/omml2mathml/pull/5

cc @ronaldtse

**Comment by CAMOBAP795** [comment]
@opoudjis @ronaldtse should we keep *.gemspec.old file?

**Comment by ronaldtse** [comment]
Probably not. Let's delete it.

**Comment by CAMOBAP795** [comment]
@ronaldtse PR updated

**Comment by CAMOBAP795** [comment]
Done
