### ISSUE TITLE
Remove RFC 6350 from examples

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-m3d#30]
Remove RFC 6350 from examples. It is not for this flavor and causing confusion such as in https://github.com/metanorma/metanorma-un/issues/43#issuecomment-603679953 . Thanks!

Replace it with https://github.com/CalConnect/csd-calspam-bcp .

**Comment by opoudjis** [comment]
An example is native to the flavour, or it does not exist. No mention of examples for now.
