### ISSUE TITLE
ubuntu still struggling with Puppetteer

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-m3d#35]
I have just eliminated Puppetteer as a dependency from CSD, RSD, NIST, OGC, IEC, ISO, UN, ITU.

It is still used in VSD, CSA, M3D, MPFD, and metanorma gem; and in those gems, it is now causing difficulties for Ubuntu:

https://github.com/metanorma/metanorma-m3d/runs/605044096?check_suite_focus=true

**Comment by CAMOBAP** [comment]
Looks like not actual anymore

**Comment by opoudjis** [comment]
Alex D has initiated work creating XSL:FO PDF for M3D and MPFD, and there is already a stylesheet for CSA. PDF has been disabled for VSD. You are correct.
